language: objective-c
osx_image: xcode11

before_install:
  - brew update
  - brew install carthage

script:
  - cd MLFairy
  - carthage update --cache-builds --new-resolver --configuration Debug
  - xcodebuild test -scheme 'MLFairy iOS' -project 'MLFairy.xcodeproj' -sdk iphonesimulator -destination "name=iPhone X"