language: objective-c

matrix:
  include:
  - osx_image: xcode10.2 
    env: 
      - SDK="iphonesimulator" 
      - DESTINATION="OS=12.2,name=iPhone Xs"
  - osx_image: xcode10.2 
    env: 
      - SDK="macosx" 
      - DESTINATION="arch=x86_64" 
  - osx_image: xcode10.2 
    env: 
      - SDK="appletvsimulator" 
      - DESTINATION="OS=12.2,name=Apple TV 4K (at 1080p)"

cache:
  directories:
  - MLFairy/Carthage

before_install:
  - brew update
  - brew install carthage
  - gem install xcpretty

script:
  - set -o pipefail
  - carthage update --cache-builds --new-resolver --configuration Debug --project-directory MLFairy
  - xcodebuild test -scheme "MLFairy" -workspace "MLFairy.xcworkspace" -sdk $SDK -destination "$DESTINATION" | xcpretty
