language: objective-c

matrix:
  include:
  - osx_image: xcode11

cache:
  directories:
  - MLFairy/Carthage

before_install:
  - brew update
  - brew install carthage
  - gem install xcpretty

script:
  - cd MLFairy
  - carthage update --cache-builds --new-resolver --configuration Debug
  - xcodebuild test -scheme 'MLFairy iOS' -project 'MLFairy.xcodeproj' -sdk iphonesimulator