language: objective-c

matrix:
  include:
  - {osx_image: xcode10.2, env: SCHEME="MLFairy iOS" SDK="iphonesimulator" DESTINATION="OS=12.2,name=iPhone Xs"}
  - {osx_image: xcode11,   env: SCHEME="MLFairy iOS" SDK="iphonesimulator" DESTINATION="OS=13.0,name=iPhone Xs"}

cache:
  directories:
  - MLFairy/Carthage

before_install:
  - brew update
  - brew install carthage
  - gem install xcpretty

script:
  - cd MLFairy
  - carthage update --cache-builds --new-resolver --configuration Debug
  - xcodebuild test -scheme $SCHEME -project 'MLFairy.xcodeproj' -sdk $SDK -destination "$DESTINATION"
