language: objective-c

matrix:
  include:
  - {osx_image: xcode11,   env: DEVICE="iPhone Xs" VERSION=13.0 PLAT=iOS}
  - {osx_image: xcode10.2, env: DEVICE="iPhone Xs" VERSION=12.2 PLAT=iOS}

cache:
  directories:
  - MLFairy/Carthage

before_install:
  - brew update
  - brew install carthage
  - gem install xcpretty

script:
  - cd MLFairy
  - carthage update --cache-builds --new-resolver --configuration Debug
  - xcodebuild test -scheme 'MLFairy iOS' -project 'MLFairy.xcodeproj' -sdk iphonesimulator -destination "platform=$PLAT Simulator,name=$DEVICE,OS=$VERSION"
